import { Anuphan, Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";
import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import Nav from '@/components/nav';
import Footer from '@/components/footer';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const nextConfig = {
  scrollRestoration: true,
  experimental: {
      scrollRestoration: true,
  },
};

const anuphan = Anuphan({
  subsets: ['latin'],
  display: 'swap',
})
 
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export default async function RootLayout({ children }: {children: React.ReactNode;}) {

  return (
    <html lang="pt-br">
      <body>
        <Nav/>
        {children}
        <Footer/>
      </body>
      <SpeedInsights />
    </html>
  );
}
